### ISSUE TITLE
Register new resource

### ISSUE THREAD

**Issue by prquinlan** [biobankinguk/biobankinguk#589] opened 2024-04-07 17:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I go to register, and then submit and it fails. 
<img width="1248" alt="Screenshot 2024-04-07 at 18 34 17" src="https://github.com/biobankinguk/biobankinguk/assets/22982046/48e0b783-1e13-484d-8437-90964dcda645">
<img width="1230" alt="Screenshot 2024-04-07 at 18 34 23" src="https://github.com/biobankinguk/biobankinguk/assets/22982046/63e8bcb1-461b-4cfa-8ee2-eee9e3ee7a5a">

### Expected Behavior

That it would not fail, or give a more sensible error message

### Steps To Reproduce

Go here:
https://dev.directory.biobankinguk.org/Register/Biobank

Enter details and submit

### Environment

```markdown
- OS:
- Other environment details:
```

**Comment by beforan** [comment] 2024-05-02 12:10
Confirmed this behaviour.

This is crashing when trying to send email, despite other areas of the app sending email successfully on this environment.

**Comment by AndyRae** [comment] 2024-07-23 08:42
Code for sending email here: 

https://github.com/biobankinguk/biobankinguk/blob/5fa2686564da52245de53d2633c9d31088964b31/app/Directory/Services/EmailServices/EmailService.cs#L137C1-L155C10

As emails work otherwise - is the error just before sending maybe? I'll have further detail when I have environment access. 

Possibly related, but I think this is line is wrong : 
```
var userEmails = _userManager.GetUsersInRoleAsync(Role.BiobankAdmin).Result
                .Select(x => new EmailAddress(x.Email)).ToList(); 
```
This gets all users who are a Biobank admin. 

But in V3 this was any `ADAC` user:
https://github.com/biobankinguk/biobankinguk/blob/39fc779927cd1633ddcce7e3a97c7b64e5260310/src/Directory/Services/EmailService.cs#L34

So I think the filter should be `Role.DirectoryAdmin`, looks like ADAC was mistranslated to Biobank admin here. There is a possibility then in the dev environment that there is an Biobank admin user who does not have an email address, and therefore the app is trying to send to a user without an email address, and throws an error. But just a theory.

**Comment by blargly** [comment] 2024-07-24 21:05
Looks like everyone was being emailed - we will need to potentially follow up and apologise to anyone affected.

This is now fixed to directory admin only and appears to be running against the dev DB successfully.

**Closed** 2024-07-25 11:29 UTC
Labels: 🐛 bug
